### PR TITLE
[WIP] Major release TODO WIP

### PR DESCRIPTION
**Pull request by brodybits**
### Platforms affected

macOS ("osx")

### What does this PR do?

- ~~remove `node_modules` from repo~~ _(now done in `master` branch)_
- ~~drop `uncrustify` _as well as `coffee-script` & `nodeunit` from devDependencies (evidently not needed)_~~ _(now done in `master` branch)_
- ~~migrate from jasmine-node to jasmine~~ _(now done in `master` branch)_
- ~~upgrade the following dependencies & devDependencies:~~ _(now done in `master` branch)_
  - ~~`cordova-common`~~
  - ~~`xcode` ref: #48~~
  - ~~`eslint`~~
  - ~~`nodeunit`~~
- ~~_remove `bundledDependencies`_~~ _(now done in `master` branch)_
- ~~_explicitly add `plist@3` dep_~~ _(moved to a separate PR)_
- ~~_update `jasmine` & `tmp` devDeps_~~ _(now done in `master` branch)_
- ~~_remove outdated `tests/.jshintrc`_~~ _(now done in `master` branch)_
- _**some** eslint updates & fixes, **now** based on 35fc60382b012dc8e06bc7a61434486f877761b7 in `master` branch_

_eslint TODO item(s):_

- [ ] _`tests/CordovaLibTests/CordovaLibApp/www` seems to have some old artifacts that were removed in cordova-ios_
- [ ] _resolve eslint issues in `tests/CordovaLibTests/CordovaLibApp/www/tests.js` & `tests/cdv-test-project/www`_
- [ ] _remove `--rule` ignoring options from `eslint:cdvlibtests` & `eslint:cdvtestwww` scripts in package.json_

_General TODO item(s):_

- [x] ~~_completely disable deprecated Node.js 4 & mark major release_~~ _(done in `master` branch)_
- [ ] _new major release of cordova-common, using plist@3 and check for any other outdated dependencies_
- [ ] _upcoming xcode@1.0.1 version (not yet available) with dependency fixes from apache/cordova-node-xcode#10_
- [ ] _check `npm outdated` & resolve **any** outdated deps_
- [ ] _try `npm-check` & resolve any other outdated deps_

### What testing has been done on this change?

_Test TODO items after some recent updates:_

- [ ] `npm test` passes on mac
- [ ] `cordova run osx` working on new project created by `cordova create` and "osx" platform added by `cordova platform add https://github.com/brodybits/cordova-osx#cb-update-wip1`
- [ ] passes the `cordova-sqlite-storage` test suite with `cordova-sqlite-storage` added by `cordova plugin add cordova-sqlite-storage` (using Xcode to run)

_General test TODO item(s):_

- [ ] enable test of `npm test` items on Travis CI

### Checklist

- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~
- ~~Added automated test coverage as appropriate for this change.~~

### CODE REVIEW

**Comment by brodybits** [comment]
Outdated `coffee-script` also removed (*tested*).

**Comment by shazron** [comment]
Sounds good to me -- don't forget the major version update

**Comment by brodybits** [comment]
Good point @Shazron!

**Comment by tripodsan** [comment]
+1

**Comment by brodybits** [comment]
Recent updates (see description):
- package*.json remove nodeunit devDep
- package.json remove bundledDependencies
- explicitly add plist@3 dep
- Update jasmine & tmp devDeps

**Comment by brodybits** [comment]
I just moved the explicit plist@3 dependency update to #66 and rebased the eslint updates on 35fc603 in `master` branch. (All other changes are now in `master` branch). Some but not all eslint updates proposed here were incorporated in merged PR #61. Some other TODO items still remain.

**Comment by erisu** [comment]
Closing this PR as the changes are in master and the latest major release.

**Pull request closed without merging**
