### PR TITLE
ESLint Dependencies Update, Configure and Corrections

### PR DESCRIPTION
**Pull request by erisu**
### Platforms affected
none

### What does this PR do?
- Upgrades eslint related dependencies
- Updates eslint configurations
- Fixes files that did not follow eslint configured standards

### What testing has been done on this change?
- `npm run eslint`

### CODE REVIEW

**Comment by brodybits** [comment]
Looks good, adding reference to WIP PR #49 where I think most of these changes are coming from.

**Comment by brodybits** [comment]
Merged in a merge commit since I think these changes should be kept separate in the git history.

**Comment by brodybits** [comment]
P.S. A major cleanup TODO item is to use `const` whenever possible, kinda wish we did this to the `var` declarations that we touched in this PR.

**Comment by janpio** [comment]
Create an issue in apache/cordova so this can be tracked and doesn't get lost in the comments of a already merged PR @brodybits

**Comment by erisu** [comment]
@brodybits I am preparing a third PR and hopefully will submit tomorrow. That will contain code coverage, a bit of a folder structure around test specs, and also a minor refactor of the test code. Refactor will cover `const`, `let`, and arrow functions if possible. etc.

**Pull request merged**
