### PR TITLE
CB-14145 resolve npm audit issues in patch fix

### PR DESCRIPTION
**Pull request by brodybits**
### Platforms affected

mac OS ("osx")

### What does this PR do?

- Set VERSION to 4.0.2-dev & update JS snapshot to version 4.0.2-dev via coho, using local coho with apache/cordova-coho#176 for patch release support (another workaround fix pushed to apache/cordova-coho#176 was needed to get the JS snapshot to work with old version of cordova-js). Note that the indentation of package.json was changed by _use of a_ recent version of coho.
- Update the following dependencies, pinned in this patch fix, to resolve the npm audit issues:
  - cordova-common@2.2.5
  - ~~xcode@1.0.0~~ _xcode@0.9.3 (same as cordova-ios)_
- explicit plist@2.1.0 dependency in this patch fix _(wanted since plist is explicitly used by code in bin ref: GH-49)_
- pin other external dependencies in this patch fix
- use jasmine-node@^1.5.0 in devDependencies to resolve npm audit warning in this patch fix
- completely reinstall node_modules in this patch fix (ignoring `node_modules/.bin`) using the following command on npm@6.1.0: `npm install --only=production`:
- Update `CordovaLib/cordova.js` from cordova-js _versions 4.2.0, 4.2.2, and 4.2.4_
- update `bundledDependencies` to support deprecated Node.js 4 in this patch fix
- remove extra `devDependencies`: coffee-script, nodeunit, uncrustify _(GH-49)_
- fixes ported from master:
  - CB-12762: package.json reference repo on github
  - migrate jshint -> eslint, with some more eslint rules turned off in this patch fix
- add line spacing to .eslintrc.yml _(GH-49)_
- enable eslint in tests/spec ~~(with some eslint rules turned off in tests/spec for now)~~ _and resolve eslint issues in tests/spec (GH-49)_

### What testing has been done on this change?

- `npm audit` with ~~npm@6.1.0~~ _npm@6.2.0_ (latest release) shows 0 vulnerabilities
- _`npm outdated` shows no red entries_
- _`npm test` succeeds locally_
- `cordova platform add brodybits/cordova-osx#cb-14145-patch` to new Cordova project and then `cordova run osx` _succeeds_ on deprecated Node.js 4 _(npm@2.15.11)_ and Node.js 8 _(npm@5.6.0)_
- `cordova platform add brodybits/cordova-osx#cb-14145-patch` to new Cordova project and then run from Xcode _succeeds_ on deprecated Node.js 4 _(npm@2.15.11)_
- _`cordova platform add brodybits/cordova-osx#cb-14145-patch` to new Cordova project and then `cordova build osx` succeeds on deprecated Node.js 4 (npm@2.15.11)_
- ~~TODO: check that Travis CI which includes `npm test` task passes~~ _(skipping this step since other changes would be needed for this project to pass its tests on Travis CI)_

### Checklist

- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected. (with some exceptions)
- ~~Added automated test coverage as appropriate for this change.~~

### CODE REVIEW

**Comment by brodybits** [comment]
> Any chance we can stop bundling to clean some of this up?

Bundling is done to support Node.js 4, which we know is deprecated but cannot be dropped in a patch release. Hope we can remove the bundled node_modules from master in the near future for major release.

For this kind of a change I would generally suggest checking each of the individual commits.

Thanks @purplecabbage!

**Comment by brodybits** [comment]
I would like to make one more update to include xcode@1.0.1 with `npm audit` fixes in apache/cordova-node-xcode#10. Apologies for any possible confusion.

**Comment by tripodsan** [comment]
can't we fix this together with #48 and #49 to get rid of the bundled node_modules ?

**Comment by dpogue** [comment]
We will remove the bundled node_modules in the next major version, but we can't do that in a patch release because it breaks compatibility with older versions of the cordova tooling.

**Comment by brodybits** [comment]
Merged with a couple more updates:
- using xcode@0.9.3 (same as cordova-ios@4.5.5)
- resolve eslint issues in tests/spec

Also checked that `npm outdated` shows no red entries, other test items repeated.

See updated description for more details.

**Pull request merged**
