### PR TITLE
Fix OS X, see CB-7143

### PR DESCRIPTION
**Pull request by hypery2k**
Following instructions as per:
https://github.com/apache/cordova-osx
"Add the Cordova OSX Platform the a CLI project" [sic]
does not work.

### CODE REVIEW

**Comment by hypery2k** [comment]
see discussion here: https://issues.apache.org/jira/browse/CB-7143

**Comment by gpetrov** [comment]
@shazron could you pickup this one? and revive Cordova OSX - having a native Mac Apps with Cordova is a great feature next to all other platforms!

**Comment by shazron** [comment]
I'm waiting on @onflapp for this one

**Comment by AltiusRupert** [comment]
@hypery2k see https://github.com/onflapp/cordova-osx for fixes

**Comment by hypery2k** [comment]
is it possible that within the next cordova release OS X is officially supported?

**Comment by tripodsan** [comment]
I think that @onflapp's branch is a bit outdated. I can revisit his changes and see what needs to be updated. it is probably easier to migrate the iOS platform from scratch. @shazron  WDYT?

**Comment by hypery2k** [comment]
Any news?

**Comment by tripodsan** [comment]
as I wrote in the dev list:
> I created a pull request that updates the readme and provides the
> new node.js based scripts. see https://github.com/apache/cordova-osx/pull/13

> and a 2nd pull request to add the osx platform the cordova-lib: https://github.com/apache/cordova-lib/pull/278

those basically bring the osx version back on track with the current nodejs based scripts. once those are in, I will incorporate some of the changes of @onflapp.

**Pull request closed without merging**
