### PR TITLE
Upgrade cordova common

### PR DESCRIPTION
**Pull request by erisu**
### Platforms affected
osx

### What does this PR do?
- Bumps cordova-common to ^2.2.5

### What testing has been done on this change?
- `npm test`

### CODE REVIEW

**Comment by erisu** [comment]
Commits cherry-picked from @brodybits' PR #49

**Comment by erisu** [comment]
There is no common@3 in the NPM registry.  If I do that now, then tests will fail.
If this PR is not pushed, then NPM audit will always show security risk until we do a major release.
@brodybits

**Comment by brodybits** [comment]
Since cordova-common@3.0.0-nightly versions are already published, I would suggest the following alternatives:
- cordova-common@3.0.x
- cordova-common@3.x.x
- cordova-common@^3.0.0-nightly (*should* match)
- cordova-common@^3.0.0-alpha (should match)

**Comment by erisu** [comment]
From the dev mailing list discussion, I believe it was decided to not use nightly builds. If this is correct can the PR now be accepted so we can fix at least the audit? And worry about the version bump at release time?

**Comment by janpio** [comment]
Nothing here that could block a merge - if there is a _better_ way to do things, this can be done in a new, additional PR anyway.

**Comment by brodybits** [comment]
Fine with me

**Pull request merged**
