### PR TITLE
Remove Unused Dependencies & update tmp

### PR DESCRIPTION
**Pull request by erisu**
### Platforms affected
none

### What does this PR do?
- Remove unused dependencies ~~and old files~~
- Update tmp dependency

### What testing has been done on this change?
- `npm test`
- `cordova run osx`
- `cordova build osx`

### CODE REVIEW

**Comment by brodybits** [comment]
Adding reference to WIP PR #49 where these changes seem to come from

**Comment by erisu** [comment]
@brodybits Rebasing now and fixing the conflict.

**Comment by brodybits** [comment]
Thanks @erisu for raising this one (PR #62) and #61 which seem to integrate some of the work I did in WIP PR #49. I am very happy that you took the initiative, considering that I don't have much time to work on it right now.

As a general rule please feel free to do this for any WIP PRs that you see lying around. In case of any questions I would favor discussing within the WIP PR itself for best tracking. I think private chats are the worst for tracking of work, discussions, agreements, etc.

I will approve this PR now, would probably favor a squash merge.

**Comment by brodybits** [comment]
@erisu can you rebase it again? I just removed `tests/.jshintrc` in PR #63.

**Comment by erisu** [comment]
@brodybits Thank for the review, I will go ahead and squash merge now. 

Also, as I mentioned in https://github.com/apache/cordova-osx/pull/61, another PR will be in the pipeline soon for creating code coverage, code refactor (`const`, `let`, etc), and test spec organization.

**Pull request merged**
