### PR TITLE
set public CDVWindowSizeCommand.h

### PR DESCRIPTION
**Pull request by giuseppelt**
### Platforms affected
OSX

### Motivation and Context

Actually plugins can not use cordova resize funcions, because they're not "exported". Thus plugin can not leverage the work of cordova framework.

### Description

To use cordova window resize functions, the command must be public, that is, callable by plugins. This change just make accessible the header.

Example of a plugin:
```swift
#import <Cordova/CDVWindowSizeCommand.h> // <--- to import the header must be public

- (void) makeFullscreen: (CDVInvokedUrlCommand *)command {
    BOOL fullscreen = [[command argumentAtIndex:0] boolValue];

    NSWindow* window = self.webView.window;
    if (fullscreen == NO) {
        [CDVWindowSizeCommand removeFullScreen:window];
    } else {
        [CDVWindowSizeCommand makeFullScreen:window];
    }
    
    [self.commandDelegate sendPluginResult:[CDVPluginResult resultWithStatus:CDVCommandStatus_OK] callbackId:command.callbackId];
}

```

### Testing

No test needed

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [x] I added automated test coverage as appropriate for this change
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by NiklasMerz** [comment]
Is this still an issue? I am not really familiar with this platform but current master branch compiles just fine.

**Comment by giuseppelt** [comment]
Hi, this patch is not about compilation, is about making public a header which is private right now.
The header inquestion allows plugins to leverage cordova own window resize function.

**Comment by NiklasMerz** [comment]
Sorry I got confused with the other issue. Let's leave this open for other reviews.

**Comment by NiklasMerz** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.

**Pull request closed without merging**
