### PR TITLE
added support for native calls into javascript for osx

### PR DESCRIPTION
**Pull request by kusog**
This change adds support for OSX native code to call back into the javascript, which is perfect for allowing OSX main menus and other native controls to trigger actions within the javascript.

### CODE REVIEW

**Comment by tripodsan** [comment]
thanks! can you add an example or test case of how this is used?

**Comment by kusog** [comment]
I am not clear on the best way to write tests for that. I think it could go into the CordovaLibTests but am not too familiar with the setup on that.  I could show in example, but the nature of the change is best shown in something like a main menu item calling a method in JS.  Somewhere there needs to be some objective-c that wants to call the JS first, not as a callback from a call initiated by JS.

I am using it to have a real main menu and some other things for a more native experience.  

Given all that, I am not sure the best way to proceed.

**Comment by tripodsan** [comment]
ok. I think of something along the lines of:
https://github.com/apache/cordova-osx/blob/master/tests/CordovaLibTests/TestPlugin.m#L32

**Comment by VPantaleo** [comment]
Hi, 

this means that I can use JavaScript for Automation on Yosemite ?

how can I do to send mail, for example ?

Thanks

**Comment by tripodsan** [comment]
> this means that I can use JavaScript for Automation on Yosemite ?
no. this means, you can call cordova from the native shell code.

**Comment by tripodsan** [comment]
@kusog I still don't really understand why you need this. can you provide a code example of how this is used?

please note, that compared to iOS, we can execute javascript directly in the webview, eg:

```
    NSString* testId = [self.webView stringByEvaluatingJavaScriptFromString:@"runTests()"];
```

if you need more, we would also need to add more methods to the `CDVBridge` to simplify the bindings.

**Comment by VPantaleo** [comment]
Hi,

I'm making an application in apache cordova os-x
I need to send mail by opening the app "Mail" of OS-X

I want to use JavaScript for Automation, can I do it?

**Comment by tripodsan** [comment]
@VPantaleo, I was asking @kusog of how we wants to use this change.

if you want to send a mail by opening mail app, you probably should write a plugin that allows you to do that. I would probably use automation (i.e apple script or similar) to control the mail app, and use the cordova side to launch the automation script. or maybe you can do something similar like this: https://github.com/franzheidl/atom-applescript

**Comment by tripodsan** [comment]
closing due to lack of response.

**Pull request closed without merging**
